name: release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install and Upgrade
      run: |
        python -m pip install --upgrade pip xpip-build xpip-upload
        python -m pip --version
        python -m pip list
    - name: Build and Test
      run: |
        make build install test
    - name: Upload to PyPI
      run: |
        xpip-upload --token ${{ secrets.PYPI_TOKEN }} dist/*

  pypi-index:
    needs: pypi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install from PyPI
        run: |
          python -m pip install -r requirements.txt
          PKGNAME=$(python setup.py --name)
          VERSION=$(python setup.py --version)
          while true; do python -m pip install $PKGNAME==$VERSION && break || sleep 5; done
